/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Público de propósito: precisa limpar o cookie mesmo com sessão expirada.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Fora da trava de troca: o front precisa ler ``mustChangePassword``.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_parameters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parameters/{chave}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar */
        put: operations["atualizar_api_parameters__chave__put"];
        post?: never;
        /** Restaurar */
        delete: operations["restaurar_api_parameters__chave__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parameters/{chave}/credencial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar Credencial */
        put: operations["atualizar_credencial_api_parameters__chave__credencial_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protheus-db/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description O que está configurado. Nunca devolve a senha, só se ela existe.
         */
        get: operations["config_api_protheus_db_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protheus-db/tabelas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tabelas */
        get: operations["tabelas_api_protheus_db_tabelas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protheus-db/tabelas/{nome}/colunas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Colunas */
        get: operations["colunas_api_protheus_db_tabelas__nome__colunas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protheus-db/consultar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar
         * @description Executa a consulta escrita no console.
         *
         *     POST e não GET, apesar de ser leitura: o SQL vai no corpo. Em query string
         *     ele apareceria no log do servidor e no histórico do navegador, e consulta
         *     ao ERP pode conter código de cliente, valor e nome.
         */
        post: operations["consultar_api_protheus_db_consultar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AtualizarCredencialInput */
        AtualizarCredencialInput: {
            /** Usuario */
            usuario: string;
            /** Senha */
            senha: string;
        };
        /** AtualizarParametroInput */
        AtualizarParametroInput: {
            /** Value */
            value: string;
        };
        /**
         * ColunaBanco
         * @description Uma coluna, como o dicionário físico a descreve.
         */
        ColunaBanco: {
            /** Nome */
            nome: string;
            /** Tipo */
            tipo: string;
            /** Tamanho */
            tamanho: number | null;
            /** Aceitanulo */
            aceitaNulo: boolean;
        };
        /** ConsultaSqlInput */
        ConsultaSqlInput: {
            /** Sql */
            sql: string;
            /**
             * Limite
             * @default 500
             */
            limite: number;
        };
        /** ConsultaSqlResult */
        ConsultaSqlResult: {
            /** Ok */
            ok: boolean;
            /** Colunas */
            colunas: string[];
            /** Linhas */
            linhas: {
                [key: string]: unknown;
            }[];
            /** Totallinhas */
            totalLinhas: number;
            /** Truncado */
            truncado: boolean;
            /** Duracaoms */
            duracaoMs: number;
            /** Erro */
            erro: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginInput
         * @description Credenciais do login.
         *
         *     O e-mail NÃO passa por validação de formato aqui, e isso é deliberado. No
         *     login ele é apenas a chave de busca: recusar antes de consultar não protege
         *     nada — a senha ainda precisaria conferir — e o validador do Pydantic é mais
         *     rígido que o do backend anterior. Ele recusa domínio de uso interno
         *     (``.local``, por exemplo), que o ``zod.email()`` aceitava. Manter o rigor
         *     aqui trancaria para fora qualquer conta em domínio interno já cadastrada.
         *
         *     Formato de e-mail se valida no CADASTRO do usuário, onde recusar é barato e
         *     a pessoa pode corrigir. Ver ``CriarUsuarioInput``.
         */
        LoginInput: {
            /** Email */
            email: string;
            /**
             * Password
             * @description Senha em texto, sobre TLS
             */
            password: string;
        };
        /**
         * ParametroPublico
         * @description Um parâmetro como a tela o vê.
         *
         *     NÃO TEM O VALOR DO SEGREDO. Para tipo SECRET e CREDENTIAL, ``value`` volta
         *     nulo e ``temValor`` diz se algo está guardado. Mascarar seria pior que
         *     omitir: sugere que existe um jeito de ler pela API.
         */
        ParametroPublico: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string | null;
            /** Group */
            group: string;
            /** Type */
            type: string;
            /** Value */
            value: string | null;
            /** Defaultvalue */
            defaultValue: string | null;
            /** Issecret */
            isSecret: boolean;
            /** Temvalor */
            temValor: boolean;
            /** Usuario */
            usuario?: string | null;
            /** Updatedby */
            updatedBy: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ProtheusDbConfig
         * @description O que está configurado. A senha nunca aparece aqui, nem mascarada.
         */
        ProtheusDbConfig: {
            /** Host */
            host: string;
            /** Porta */
            porta: number;
            /** Banco */
            banco: string;
            /** Usuario */
            usuario: string;
            /** Senhaconfigurada */
            senhaConfigurada: boolean;
            /** Criptografia */
            criptografia: boolean;
            /** Certificadoconfiavel */
            certificadoConfiavel: boolean;
            /** Timeoutsegundos */
            timeoutSegundos: number;
            /** Configurado */
            configurado: boolean;
            /** Pendencias */
            pendencias: string[];
        };
        /** SessionResponse */
        SessionResponse: {
            user: components["schemas"]["SessionUser"];
        };
        /** SessionUser */
        SessionUser: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Mustchangepassword */
            mustChangePassword: boolean;
        };
        /**
         * TabelaBanco
         * @description Uma tabela do banco, para navegar antes de escrever a consulta.
         */
        TabelaBanco: {
            /** Nome */
            nome: string;
            /** Esquema */
            esquema: string;
            /** Registrosestimados */
            registrosEstimados: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_parameters_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroPublico"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_api_parameters__chave__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chave: string;
            };
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarParametroInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroPublico"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restaurar_api_parameters__chave__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chave: string;
            };
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroPublico"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_credencial_api_parameters__chave__credencial_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chave: string;
            };
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarCredencialInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroPublico"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_api_protheus_db_config_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtheusDbConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tabelas_api_protheus_db_tabelas_get: {
        parameters: {
            query?: {
                busca?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TabelaBanco"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    colunas_api_protheus_db_tabelas__nome__colunas_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nome: string;
            };
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColunaBanco"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_api_protheus_db_consultar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultaSqlInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultaSqlResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
